### ISSUE TITLE
Antigen install issue

### ISSUE THREAD

**Issue by wallace11** [mattmc3/zshrc.d#1]
Apparently antigen doesn't know how to deal with `main` branches.
Upon installation you get an error:
```
Error! Activate logging and try again
```

So in order to install it one must specify a branch: `antigen bundle mattmc3/zshrc.d@main`

**Comment by mattmc3** [comment]
Looks like you're right. Antigen isn't really an active project and looks like this issue has been open since October: https://github.com/zsh-users/antigen/issues/717

I'll update the readme to specify the branch. Thanks for the info.
